### PR TITLE
Fix windows store extension by upgrading dependencies

### PR DESCRIPTION
**Pull request by louis-wuitton**

### CODE REVIEW

**Comment by louis-wuitton** [comment]
Upgrading our dependency packages to resolve issue https://github.com/microsoft/windows-dev-center-vsts-extension/issues/104.

Code change includes:
1. Switch from "azure-storage" npm package to "@azure/storage-blob" package.
2. Update gulp version to 4.0.2 and also update its corresponding gulp file
3. Update other outdated dependency packages

**Comment by louis-wuitton** [comment]
This pull request includes various changes to improve the codebase, simplify the code, and update dependencies. The most important changes include simplifying the code and improving readability in the `gulpfile.js`, updating the `uploadZip` function in `apiHelper.ts` to use the `@azure/storage-blob` package, and updating dependencies in `package.json`.

Main changes:

* [`gulpfile.js`](diffhunk://#diff-25789e3ba4c2adf4a68996260eb693a441b4a834c38b76167a120f0b51b969f7L198-R196): Simplified the code and improved readability by replacing `multistream.apply` with `multidest`, adding new tasks to remove the common directory and install node dependencies, and modifying the `compile` task to include the new tasks. [[1]](diffhunk://#diff-25789e3ba4c2adf4a68996260eb693a441b4a834c38b76167a120f0b51b969f7L198-R196) [[2]](diffhunk://#diff-25789e3ba4c2adf4a68996260eb693a441b4a834c38b76167a120f0b51b969f7L179-R140) [[3]](diffhunk://#diff-25789e3ba4c2adf4a68996260eb693a441b4a834c38b76167a120f0b51b969f7L108-R82) [[4]](diffhunk://#diff-25789e3ba4c2adf4a68996260eb693a441b4a834c38b76167a120f0b51b969f7L10-L97)
* [`apiHelper.ts`](diffhunk://#diff-25789e3ba4c2adf4a68996260eb693a441b4a834c38b76167a120f0b51b969f7L198-R196): Updated the `uploadZip` function to use the `@azure/storage-blob` package instead of the `azure` package. [[1]](diffhunk://#diff-25789e3ba4c2adf4a68996260eb693a441b4a834c38b76167a120f0b51b969f7L198-R196) [[2]](diffhunk://#diff-25789e3ba4c2adf4a68996260eb693a441b4a834c38b76167a120f0b51b969f7L179-R140) [[3]](diffhunk://#diff-25789e3ba4c2adf4a68996260eb693a441b4a834c38b76167a120f0b51b969f7L108-R82) [[4]](diffhunk://#diff-25789e3ba4c2adf4a68996260eb693a441b4a834c38b76167a120f0b51b969f7L10-L97)
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L12-R36): Updated dependencies, including `azure-pipelines-task-lib` and `@azure/storage-blob`, and updated versions of `url` and `uuid` dependencies.

Other changes:

* [`tasks/common/requestHelper.ts`](diffhunk://#diff-791d67dd135fc70a1983905b62f8a491c962ff2a3779145d6cd3a046c35c2a38L6-R11): Updated the import statement and usage of the `uuid` library. [[1]](diffhunk://#diff-791d67dd135fc70a1983905b62f8a491c962ff2a3779145d6cd3a046c35c2a38L6-R11) [[2]](diffhunk://#diff-791d67dd135fc70a1983905b62f8a491c962ff2a3779145d6cd3a046c35c2a38L131-R129)
* [`tasks/store-flight/task.json`](diffhunk://#diff-81fe7c61e622a4192232ed30a7a9b4c1015331438efc251dfcb4ca8f0ddc5eeaR172-R179): Added support for Node 10 and Node 16 in the `store-flight` task configuration and updated the `Patch` version. [[1]](diffhunk://#diff-81fe7c61e622a4192232ed30a7a9b4c1015331438efc251dfcb4ca8f0ddc5eeaR172-R179) [[2]](diffhunk://#diff-81fe7c61e622a4192232ed30a7a9b4c1015331438efc251dfcb4ca8f0ddc5eeaL18-R20)
* [`vss-extension.json`](diffhunk://#diff-81f89915829f6a1a40da4191994bd65d445564779e6bea3e87dafc0ad7abb6e2L4-R9): Updated the version of the extension and changed the category.
* [`tasks/common/apiHelper.ts`](diffhunk://#diff-d633302c1504b696436e5eb8702e0ea72157dde7311de23cacd2bc841f7a8955L16-R16): Updated import statements, removed typings references, and replaced the previous implementation of the `uploadZip` function. [[1]](diffhunk://#diff-d633302c1504b696436e5eb8702e0ea72157dde7311de23cacd2bc841f7a8955L16-R16) [[2]](diffhunk://#diff-d633302c1504b696436e5eb8702e0ea72157dde7311de23cacd2bc841f7a8955L6-L7) [[3]](diffhunk://#diff-d633302c1504b696436e5eb8702e0ea72157dde7311de23cacd2bc841f7a8955R447-R464)
* [`tasks/common/inputHelper.ts`](diffhunk://#diff-9df50906bd5dda6e83f057506d7d14ab0490328e1ce5f13c47a7c86e8e7f4528L5-R5): Updated the import statement for the `tl` library.
* [`tasks/store-publish/publishUi.ts`](diffhunk://#diff-58f3e07575e6fb3ac6b013e0f9eb0baa39be0f4be3e75bbecb9a7067377ea4a7L12-R12): Updated the import statement for the `tl` library.
* [`tasks/store-flight/flightUi.ts`](diffhunk://#diff-0819e9bf3c7800ee3c271de93b40befe782a0e788703e1a63303133fdfca0ee0L12-R12): Updated the import statement for the `tl` library.
* [`tasks/store-publish/task.json`](diffhunk://#diff-32eb5937231f80eb4f68dfeb69657ed6b9869ce485b4be2f614af8772718f0e8L18-R20): Updated the minimum agent version required and added new targets. [[1]](diffhunk://#diff-32eb5937231f80eb4f68dfeb69657ed6b9869ce485b4be2f614af8772718f0e8L18-R20) [[2]](diffhunk://#diff-32eb5937231f80eb4f68dfeb69657ed6b9869ce485b4be2f614af8772718f0e8R193-R200)
* [`tasks/store-flight/flight.ts`](diffhunk://#diff-eba980b8360327047df8d226f9479f800e8e9bb9b97636a1ab99ec54947e3a09L6-R10): Updated the import statement.
* [`tasks/store-publish/publish.ts`](diffhunk://#diff-c14ffe7a9e1e5914602f24063e0cee4c437682ffce62caf7ce30794a0a562935L6-R13): Updated the import statement.

**Review by junyin-ms — APPROVED** [review]
Looks good.

**Comment by jamers99** [comment]
@louis-wuitton @junyin-ms hey guys! I'm getting this when using the Publish task! We can't use our pipelines for releases!
image

I've tried both `MS-RDX-MRO.windows-store-publish.publish-task.store-publish@0` and `store-publish@0`
image

I'm guessing it's from the change in: tasks/store-publish/task.json

**Comment by louis-wuitton** [comment]
> @louis-wuitton @junyin-ms hey guys! I'm getting this when using the Publish task! We can't use our pipelines for releases! image
> 
> I've tried both `MS-RDX-MRO.windows-store-publish.publish-task.store-publish@0` and `store-publish@0` image
> 
> I'm guessing it's from the change in: tasks/store-publish/task.json

Thank you for catching this issue. I have added a hotfix to the extension and the storepublish task should be good now.

**Pull request merged**
