### PR TITLE
Change image type list and endpoint type

### PR DESCRIPTION
**Pull request by louis-wuitton**

### CODE REVIEW

**Comment by jamers99** [comment]
@louis-wuitton this did not resolve the issue (or maybe it just made a new one). See my comment: https://github.com/microsoft/windows-dev-center-vsts-extension/issues/87#issuecomment-651766981

**Comment by jamers99** [comment]
Interesting. I deleted the service connection and recreated it, then it worked.

This is not good that this is not backwards compatible...

**Comment by jamers99** [comment]
This is still causing problems when trying to submit to a flight. It doesn't work.
https://github.com/microsoft/windows-dev-center-vsts-extension/issues/87#issuecomment-652040664

**Comment by louis-wuitton** [comment]
Seems like the flight task version wasn't bumped up correctly and there might be a mismatch, so the flight task didn't pick up the changes. I bumped it up higher

**Comment by jamers99** [comment]
@louis-wuitton that did not fix the issue. I'm getting this now:
##[error]Status 500: {"code":"InternalServerError","data":[],"details":[],"innererror":{"code":"UnknownInternalFailure","data":[],"details":[],"message":"The service has encountered an unknown internal server error: "},"message":"An internal server error occurred while processing the operation.","source":"Ingestion Api"} CorrelationId: 37fa85ff-7e92-4835-a91d-5b52834247d5

This is very important in our deployment pipeline. Please make sure this is tested and works before updating it...

**Comment by jamers99** [comment]
Okay, just looking at the logs, looks like it started the submission:
```
Obtaining app information...
Obtaining flight resource for flight Beta in app 9NTSH9RQ89KR
Creating flight submission...
Submission https://developer.microsoft.com/en-us/dashboard/apps/9NTSH9RQ89KR/submissions/1152921505690598125 was created successfully
Deleting old packages...
Updating package delivery options...
Updating flight submission...
Creating zip file...
Uploading zip file...
Successfully uploaded file!
Committing flight submission...
##[error]Status 500: {"code":"InternalServerError","data":[],"details":[],"innererror":{"code":"UnknownInternalFailure","data":[],"details":[],"message":"The service has encountered an unknown internal server error: "},"message":"An internal server error occurred while processing the operation.","source":"Ingestion Api"} CorrelationId: 37fa85ff-7e92-4835-a91d-5b52834247d5
**

**Comment by jamers99** [comment]
I deleted the submission that the previous attempt created, then tried running it again and now the logs look like this:
```
Obtaining app information...
Obtaining flight resource for flight Beta in app 9NTSH9RQ89KR
Creating flight submission...
##[error]Status 500: {"code":"InternalServerError","data":[],"details":[],"innererror":{"code":"UnknownInternalFailure","data":[],"details":[],"message":"The service has encountered an unknown internal server error: "},"message":"An internal server error occurred while processing the operation.","source":"Ingestion Api"} CorrelationId: eafc7248-8ebf-48a1-bb9e-2d6cef93ce31
```

**Comment by tesar-tech** [comment]
It's this one: https://github.com/microsoft/windows-dev-center-vsts-extension/issues/86 , probably not caused by extension.

**Pull request merged**
